apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
    - image: nginx:alpine
      name: test-container
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      volumeMounts:
        - mountPath: /var/log/nginx
          name: vol
  volumes:
    - name: vol
      emptyDir: {}
