apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-volume
  labels:
    mysql: ready
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce # solo se puede usar una ves al tiempo, osea dos pods no los pueden usar al tiempo
  hostPath:
    path: "/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      mysql: ready
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Initial create"
  name: mysql
  labels:
    app: mysql
spec:
  # revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456789"
        resources:
          requests:
            memory: "254Mi"
            cpu: "500m"
          limits:
            memory: "520Mi"
            cpu: "1000m"
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: vol-mysql
      volumes:
        - name: vol-mysql
          persistentVolumeClaim:
            claimName: test-pvc