apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Initial create"
  name: front-deployment-test
  labels:
    app: front
spec:
  # revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        # image: nginx:alpine
        image: nginx
        ports:
          - containerPort: 6100
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"