kind: Namespace
apiVersion: v1
metadata:
  name: limit
  labels:
    name: limit
---    
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: limit
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi