apiVersion: v1
kind: Service
metadata:
  name: loki-grafana-loadbalancer
  namespace: loki
  labels: 
    app.kubernetes.io/instance: loki
    app.kubernetes.io/name: grafana 
spec:
  type: LoadBalancer
  selector:
   app.kubernetes.io/instance: loki
   app.kubernetes.io/name: grafana 
  ports:
    - port: 80
      targetPort: 3000