apiVersion: v1
kind: Service
metadata:
  name: nginx-service-node
  labels:
    app: golang-backend
spec:
  type: NodePort
  selector:
    app: golang-backend
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 9090