apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Initial create"
  name: backend-deployment-test
  labels:
    app: backend
spec:
  # revisionHistoryLimit: 2
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        # image: nginx:alpine
        image: nginx
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
---            
apiVersion: v1
kind: Service
metadata:
  name: my-service-backend
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend # label de los pods a observar
  ports:
    - protocol: TCP
      port: 8080 # puerto que se expone
      targetPort: 80 # puerto a observar