apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Initial create"
  name: golang-frontent
  labels:
    app: golang-frontent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-frontent
  template:
    metadata:
      labels:
        app: golang-frontent
    spec:
      containers:
      - name: golang-frontent
        image: frontent-k8s-example
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "32Mi"
            cpu: "125m"
        ports:
        - containerPort: 80
---            
apiVersion: v1
kind: Service
metadata:
  name: golang-service-frontent
  labels:
    app: golang-frontent
spec:
  type: LoadBalancer
  selector:
    app: golang-frontent # label de los pods a observar
  ports:
    - protocol: TCP
      port: 8800 # puerto que se expone
      targetPort: 80 # puerto a observar