apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: memory-test
spec:
  containers:
  - name: memory-test-ctr
    image: polinux/stress
    resources:
      limits:
        memory: "200Mi"
        cpu: "500m"
      requests:
        memory: "100Mi"
        cpu: "250m"
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]
