apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: dev
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1"
        memory: "200Mi"
      requests:
        cpu: "0.5"
        memory: "100Mi"
    args:
    - -cpus
    - "2"