apiVersion: v1
kind: Pod
metadata:
  name: twocontainers
spec:
  containers:
  - name: cont1
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo cont1 > index.html && python -m http.server 8081']
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"
  - name: cont2
    image: python:3.6-alpine
    command: ['sh', '-c', 'echo cont2 > index.html && python -m http.server 8082']
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "64Mi"
        cpu: "100m"